services:
  parabank:
    image: parasoft/parabank:latest
    ports:
      - "8080:8080"
    environment:
      - DB_PERSIST=true
      - DB_PORT=9002
    volumes:
      - "/Users/A107498214/Projekty/Java/parabank/target/parabank-5.0.0-SNAPSHOT.war:/usr/local/tomcat/webapps/testathon.war"