services:
  parabank:
    image: parasoft/parabank:latest          # verejný tomcat image s JDBC
    ports:
      - "8080:8080"
    environment:
      - DB_PERSIST=true
      - DB_PORT=9002
    volumes:                                 # ⬅︎ mount lokálneho WAR
      - ./target/parabank-5.0.0-SNAPSHOT.war:/usr/local/tomcat/webapps/parabank.war